### ISSUE TITLE
Sqlite in non-docker / postgres in docker isn't a great pattern

### ISSUE THREAD

**Issue by drd0013** [Seedstars/django-react-redux-base#101]
Hello, I recently cloned this to start off a django / react project and noticed that manually running the server is using sqlite while docker is using postgres. 
Did you make this decision to avoid the cost of setting up postgres on various platforms? I'm going to switch to using postgres locally and could make a PR with those changes and update the docs a bit to at least work for mac if you would be interested.

**Comment by lfrodrigues** [comment]
Yes, we did.
