### ISSUE TITLE
many settings are tuples instead of lists, which django recommends

### ISSUE THREAD

**Issue by drd0013** [Seedstars/django-react-redux-base#102]
Installed Apps, for instance, is a tuple, and when I went to extend it in dev.py with `INSTALLED_APPS += ['sslserver']`, I ran into an error about extending a tuple with a list. I will make a PR with these changes.
https://docs.djangoproject.com/en/1.11/ref/settings/#installed-apps

**Comment by drd0013** [comment]
https://github.com/Seedstars/django-react-redux-base/pull/103

**Comment by lfrodrigues** [comment]
thanks!
