### ISSUE TITLE
Why django knox?

### ISSUE THREAD

**Issue by PeriGK** [Seedstars/django-react-redux-base#112]
Hi,

I am interested in adopting your boilerplate to an OSS of mine. Could you please give me hint why you prefered Django Knox instead of `rest_framework_simplejwt.authentication.JWTAuthentication`?

Cheers,
P.

**Comment by lfrodrigues** [comment]
Because JWT does not have a solution to force signout of all the user's sessions. 

https://stackoverflow.com/questions/42330013/jwt-token-refresh-sliding-sessions-and-signout
