### ISSUE TITLE
Support for gettext internationalization in the frontend?

### ISSUE THREAD

**Issue by mandx** [Seedstars/django-react-redux-base#27]
https://blog.sentry.io/2016/01/07/react-i18n.html

**Comment by lfrodrigues** [comment]
Thanks for comment, I'll look into that once I have some time. In other projects we're using react-intl.

**Comment by mandx** [comment]
Just to clarify, I mention gettext because Django already uses gettext, so it kind of makes sense to use the same tool to internationalize both the backend and the frontend.
