### ISSUE TITLE
Include Immutable.js?

### ISSUE THREAD

**Issue by coffenbacher** [Seedstars/django-react-redux-base#29]
I'm usually for minimal boilerplates, but with how well it works with Redux, Immutable.js has become an automatic "every project" add for my team. Anyone that's not using it with Redux is missing out, IMO!

Of course, I understand keeping the boilerplate as minimal as possible and just asking users to make their own decision as well.

**Comment by lfrodrigues** [comment]
Hey, thanks for the comment. Would you be interested in submitting a PR?
