### ISSUE TITLE
Accessing Django admin

### ISSUE THREAD

**Issue by yarnball** [Seedstars/django-react-redux-base#31]
Hi,

Sorry if it's a silly question- but I cannot access the traditional Django Admin site. has it been removed?

Thanks

**Comment by volkandkaya** [comment]
Yes, it is also not easy to put back in they have changed the user model and removed a bunch of settings.

**Comment by lfrodrigues** [comment]
We don't really need Django admin so we removed it. Feel free to submit a PR. As long as it doesn't impact our projects we can add it for the benefit of the community

**Comment by delneg** [comment]
How do we include it properly, I tried it and had a problem with it because it requires a lot of middlewares & stuff, not used in this project?

**Comment by lfrodrigues** [comment]
fixed in #43
