### ISSUE TITLE
.eslinrc

### ISSUE THREAD

**Issue by woles** [Seedstars/django-react-redux-base#32]
Hey,
that is one of the best boilerplates that I had a chance to look into. Thank you very much for it!

I think that can be quite problematic - time taking thing to create by yourself the .eslintrc file with all the rules you use. In previus version the file was included. 

Second thing - it's not a tivial thing to find a way of livereload of this project under dev. For me that sholud be included to the base. For the easiest way was to use webpack-livereload-plugin but still I wonder if it's possible to have a hot reload of that project without another server running.

Thank you one more time for this repo

**Comment by lfrodrigues** [comment]
Thanks for your comments. 

.eslintrc comes from 
```
https://github.com/Seedstars/culture/tree/master/code/validation
```
It is downloaded using
```
$ ./scripts/get_static_validation.sh
```
See **Retrieve code** section in README

As for live reload we don't have it, feel free to add it and summit PT

**Comment by woles** [comment]
Thanks, I miss that in some point.
