### ISSUE TITLE
Include django-allauth or django-rest w/ django-allauth ? 

### ISSUE THREAD

**Issue by tristant** [Seedstars/django-react-redux-base#51]

**Comment by tristant** [comment]
Allauth already has email authentication but also provides multiple providers

**Comment by lfrodrigues** [comment]
Why django-allauth?  Did you compare django-registration/django-allauth/python-social-auth ?

**Comment by tristant** [comment]
Django-registration doesn't provide social authentication which is the sort of bonus we're looking at here.
Django allauth is what django-rest-auth is based upon. Both project seem well-maintained& sponsored.
Python social auth seems nice, but I haven't used it personally, and the way the project has been handled seems a bit chaotic ( django-social-auth -> Python-social-auth ->  Python-social-auth-organization where they "expect more organised development" ).

So for a easy-setup email registration with all views, and social auth, it seems django-rest-auth (which uses django-allauth) is the best choice. 
What do you think ?

**Comment by lfrodrigues** [comment]
Usually we use python-social-auth in our project. We'll review the possibilities and get back to you.

**Comment by tristant** [comment]
Great ! Thank you for your impressive reaction time and thank you for this project !

**Comment by lfrodrigues** [comment]
We have discussed this and we really want to keep this project as simple as possible. 

Adding a a registration framework is really simple so we don't believe that it should be included. Users of our project can choose whatever they wish.
