### ISSUE TITLE
window.INITIAL_STATE is undefined

### ISSUE THREAD

**Issue by shudson250** [Seedstars/django-react-redux-base#53]
I've taken the repo and integrated Typescript with the React app, but in building the application I get an error that window.INITIAL_STATE is undefined. Is this by design?

If I had to guess, Typescript is failing here because it is never defined, whereas lazy ol Javascript would just take it and roll, and configure store would just get undefined as initial state.

I think that's it, but can someone confirm/deny?

**Comment by fgarci03** [comment]
Nice catch, we don't really need the window.INITIAL_STATE variable, as we are not rendering anything server side. Will correct it :+1:
