### ISSUE TITLE
Postgres not persisting data to shared volumes between runs

### ISSUE THREAD

**Issue by andrewglancy** [Seedstars/django-react-redux-base#57]
I'm currently running the app and populating postgres with data. I see there is a volumes entry in docker-common.yml, and assumed data would be persisted between container runs to './docker/postgres/data', but have not seen data get persisted.

Assistance on this would be greatly appreciated as I've been banging my head against my keyboard all day but still can't figure it out.

volumes:
          - ./docker/postgres/data:/var/lib/postgresql

**Comment by andrewglancy** [comment]
I've subsequently found some useful information for shared Volumes. Let me know if you have additional insights and thanks for this great project.

    https://docs.docker.com/docker-for-mac/osxfs/
    https://www.digitalocean.com/community/tutorials/how-to-work-with-docker-data-volumes-on-ubuntu-14-04

**Comment by andrewglancy** [comment]
@fgarci03 When I run docker-compose up I see another data directory is created inside the folder ./docker/postgres/data/ but nothing is persisted to this data directory. My expectation was, once everything starts, this newly created data directory should contain the posgres_data folder and that data would be persisted across app runs. This might be a false assumption.

I am testing by accessing the django-admin and creating an additional user. This user is not persisted between runs. When do this and run `docker-compose down && docker-compose up` the additional user I added is gone.  I am performing this test on MacOS.

Any insight as to why it isn't working or what I'm not understanding would be greatly appreciated.

**Comment by fgarci03** [comment]
@andrewglancy thanks for the input and research. I will fix this ASAP :)

**Comment by fgarci03** [comment]
@andrewglancy the command `docker-compose down` removes all containers, images and volumes, meaning that there will be no persistent data.

I dont't have access to a Mac, so could you try with `docker-compose stop`? Or Ctrl+C?

**Comment by andrewglancy** [comment]
Would you interested in a PR for the Readme so some other foolish soul doesn't make the same stupid mistake?

Thank you!

**Comment by fgarci03** [comment]
@andrewglancy that would be great! thanks :+1:

**Comment by fgarci03** [comment]
bump.

@andrewglancy are you still interested in submitting the PR?

**Comment by andrewglancy** [comment]
yes @fgarci03 Will do Saturday. Sorry for the delay.

**Comment by andrewglancy** [comment]
@fgarci03 https://github.com/Seedstars/django-react-redux-base/pull/60
