### ISSUE TITLE
login does not work

### ISSUE THREAD

**Issue by vincejah** [Seedstars/django-react-redux-base#59]
Hi,

I've just installed this great boilerplate (thanks a lot by the way).
Unfortunatly, when I try to login, I have the following error message: "Authentication Error: Connection Error - An error occurred while sending your data!"

Looking at the API requests, I see that an OPTIONS method is sent before POST can be executed (CORS preflight?) and Django responds with "OPTIONS /api/v1/accounts/login/ HTTP/1.0" 401 70

Do you have any idea how I could fix this problem?

Thanks!

**Comment by vincejah** [comment]
I think the reason is CORS. I was using frontend url 127.0.0.1:8000 when I was getting this error. When changing this to localhost:8000, it works properly.

Don't you think the login view should allow OPTIONS to be called without authentication?

**Comment by lfrodrigues** [comment]
Hey,
Thanks for your comments. Yes the reason was CORS. 

We would need to disable CORS to allow other URLs. I honestly don't like that solution. It's a standard security practice for CORS to block other URLs than the correctly configured one.

We'll add information on the README to make it clear to everyone which URL should be used.

**Comment by TaylanT** [comment]
same problem here. can you please describe the workaround?

**Comment by lfrodrigues** [comment]
If you look at 
https://github.com/Seedstars/django-react-redux-base/blob/master/src/static/utils/config.js#L1 
we set the request URL to localhost, so the solution is to use http://localhost:8000 in your browser

**Comment by ollie101** [comment]
Also had this problem - a quick mention in the README would be good :thumbsup:
