### ISSUE TITLE
Accessing the built-in Django admin area?

### ISSUE THREAD

**Issue by bchuey** [Seedstars/django-react-redux-base#62]
Thanks for this awesome boilerplate guys!

I have been able to set up the majority of it and things are working fine.

However, when I go to `/admin`, the response is `NOT FOUND`.

Because the routing is being handled by React/Redux now, am I not able to use the built-in Django admin functionality/features?

**Comment by ahrajabi** [comment]
I think you should go to `/admin/`.

```
urlpatterns = [
    url(r'^api/v1/accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/v1/getdata/', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),

    # catch all others because of how history is handled by react router - cache this page because it will never change
    url(r'', cache_page(settings.PAGE_CACHE_SECONDS)(base_views.IndexView.as_view()), name='index'),
]
```

**Comment by bchuey** [comment]
@ahrajabi Wow, thanks. That was simple. My other routes allow without the trailing `/`. Is that because `/admin/` is using Django urls?

**Comment by lfrodrigues** [comment]
@bchuey yes it is. Our Django URL all finish with ```/```
