### ISSUE TITLE
Is there any plan to reduce the bundle size?

### ISSUE THREAD

**Issue by MengJueM** [Seedstars/django-react-redux-base#63]
The default webpack production config will produce 5M+ bundle.js(vendor.js), it is bad idea to serve the index to such a cost, do you guys have the plan to reduce the bundle size or split them into smaller chunks?

**Comment by lfrodrigues** [comment]
If you compile javascript in production mode vendor is approx 400kb and app 300kb. Moreover, considering you typically gzip assets the size is not a problem.
