### ISSUE TITLE
When do you plan to include React Router v4?

### ISSUE THREAD

**Issue by coltonbh** [Seedstars/django-react-redux-base#65]

**Comment by coltonbh** [comment]
I believe this will change the way the app will interact with Redux.  As a beginner, it would be great to have things working with the much smoother RR4 and then move forward with that :)

**Comment by lfrodrigues** [comment]
Yes we plan to update, no clear timeline yet. In any case if you have time/want to please feel free to submit a PR :)

**Comment by rajagopalx** [comment]
👍

**Comment by lfrodrigues** [comment]
Updated in master
