### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by tanvirraj** [Seedstars/django-react-redux-base#68]
First of all Thanks for this boilerplate.

I have some issue about registration. 
when i am registration a new user how can I send activation email and activate the user. 
Thanks

**Comment by dopeboy** [comment]
Hi Tanvir - that feature is outside the scope of a boilerplate project like this.

You might be better off using a service like mailgun to achieve that.

**Comment by lfrodrigues** [comment]
@tanvirraj  as @dopeboy wrote that feature is outside of our scope. Mailgun/sendgrid/sparkpost are options for this.
