### ISSUE TITLE
Deployment Documentation

### ISSUE THREAD

**Issue by iraycd** [Seedstars/django-react-redux-base#69]
I think it would be good if it had a brief/in-depth documentation on the deployment.

**Comment by kevinluvian** [comment]
+1

**Comment by denny64** [comment]
+1

**Comment by ruffers9** [comment]
+1

**Comment by ruffers9** [comment]
Hi all, I recently deployed a project to digital ocean using this stack and although I have not used aws ec2, I imagine the setup is similar. I used an image of ubuntu 16.04 running in the cloud and followed this https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04 guide. create a virtual enviorment and pip install the py-requirements/prod.txt and make sure the settings are all switched to prod. Make a static dist bundle with the command npm run prod, making sure to alter the package.json and remove the --watch flag after the command. Let me know if you have any questions, I'm thinking about putting together a more concrete guide.

**Comment by ganisivakumar** [comment]
Hi ruffers9, please add a dep[loyment guide, i am having hard time figuring out of my own

**Comment by ganisivakumar** [comment]
In production environment, it showing a blank page, if using 'dev.py' in 'wsgi' then it is working fine, but 'prod.py' in 'wsgi' its showing blank page.
Also what to put in 'RAVEN CONFIG'.
Thanks in advance.

**Comment by ganisivakumar** [comment]
Hi ruffers9, which --watch are you referring to, please help me

**Comment by ganisivakumar** [comment]
what to do you put in nginx config file, my static files are not rendering

**Comment by lfrodrigues** [comment]
@ruffers9 added your link to our readme. thanks!

**Comment by m2jobe** [comment]
+ 1

**Comment by m2jobe** [comment]
@ruffers9 Did you put together a more concrete guide? I run into issues setting up the gunicorn service whilst following the guide

**Comment by ruffers9** [comment]
I will help you what is the problem

**Comment by m2jobe** [comment]
Thank you! I got the gunicorn service running as well as nginx but ran into this problem  when I visit localhost. 

> Uncaught SyntaxError: Unexpected token <
app.fcf0efe80bcdfeb5336f.js?fcf0efe80bcdfeb5336f:1 Uncaught SyntaxError: Unexpected token <
localhost/:7 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost/static/styles/vendor.css".

I think the issue might be that nginx can find the static files?
`[Unit]
Description=gunicorn daemon
After=network.target

[Service]
User=muhammed
Group=muhammed
WorkingDirectory=/home/muhammed/Documents/mydev/djr/src
ExecStart=/home/muhammed/Documents/mydev/djr/src/djangoreactredux/djangoreactreduxenv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/home/muhammed/Documents/mydev/djr/src/djangoreactredux/djangoreactredux.sock djangoreactredux.wsgi:application

[Install]
WantedBy=multi-user.target
`

**Comment by ruffers9** [comment]
Try building webpack without the hash

**Comment by m2jobe** [comment]
I tried building without the hash same "Uncaught SyntaxError: Unexpected token " error
