### ISSUE TITLE
css order with CommonsChunkPlugin

### ISSUE THREAD

**Issue by LennyLip** [Seedstars/django-react-redux-base#70]
How i can change order of load output css files with CommonsChunkPlugin?

Now vendor load after app. it is override app css with vendors css selectors.

**Comment by LennyLip** [comment]
Anyone? How to remove vendor css from CommonsChunkPlugin?

**Comment by lfrodrigues** [comment]
Tried to debug this but could not find a solution. The order is correct in prod but not dev.

**Comment by kjschill** [comment]
Any luck with this? I'm having the same problem, vendor.css is included after app.css.
```html
<head>
  <title>My Title</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="/static/styles/app.css?363111229df122a1cd8b" rel="stylesheet"><link href="/static/styles/vendor.css?363111229df122a1cd8b" rel="stylesheet"></head>
```

**Comment by kjschill** [comment]
I ended up using the manual sort option of `HtmlWebpackPlugin` to import the chunks in the desired order.  Updated webpack config `common.config.js` as:

```javascript
        new HtmlWebpackPlugin({
            template: path.join(__dirname, '../src/static/index.html'),
            hash: true,
            chunks: ['vendor', 'app'],
            chunksSortMode: 'manual',
            filename: 'index.html',
            inject: 'body'
        }),
```

**Comment by lfrodrigues** [comment]
Great, can you please submit a PR?
