### ISSUE TITLE
HELP - How to deploy this to AWS EC2?

### ISSUE THREAD

**Issue by denny64** [Seedstars/django-react-redux-base#72]

**Comment by ruffers9** [comment]
Hi denny64, I recently deployed a project to digital ocean using this stack and although I have not used aws ec2, I imagine the setup is similar.  I used an image of ubuntu 16.04 running in the cloud and followed this https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04 guide.  create a virtual enviorment and pip install the py-requirements/prod.txt and make sure the settings are all switched to prod.  Make a static dist bundle with the command npm run prod, making sure to alter the package.json and remove the --watch flag after the command.  Let me know if you have any questions, I'm thinking about putting together a more concrete guide.

**Comment by denny64** [comment]
Thanks for the reply @ruffers9 - I was trying to use AWS ECS but that got really complicated, so I ended up setting up an ec2 instance and ssh into that, then ran `docker-compose up` and everything worked like magic!

PS: Had to modify the dockerfile a little

**Comment by ruffers9** [comment]
denny64  From what I understand there's some performance issues you run into using docker in production.

**Comment by denny64** [comment]
@ruffers9 oh really, what kind?

**Comment by ruffers9** [comment]
denny64 I thought I read somewhere on this repo that it was not advised, but now reading more about it, it looks like it should be fine

**Comment by m2jobe** [comment]
@denny64  Hey what did you modify in the dockerfile and were you able to get it working on port 80?
