### ISSUE TITLE
how to get app up and running (out of box?)

### ISSUE THREAD

**Issue by gmaijoe** [Seedstars/django-react-redux-base#80]
Hi, I'm pretty new to this django and docker setup - what steps should i run to get the boiler site up and running out of the box?

**Comment by gmaijoe** [comment]
<img width="635" alt="screen shot 2017-08-02 at 4 15 54 pm" src="https://user-images.githubusercontent.com/7184919/28899067-eed1677a-779d-11e7-8573-a74a7da0d829.png">

**Comment by yudori** [comment]
Hey, Checkout https://github.com/Seedstars/django-react-redux-base/tree/27e65fc98730f1767dde95b08b6d9a6cc65edb4e if you'd rather not use docker

**Comment by invious** [comment]
I also followed all instructions up to `docker-compose up` and it says that `/django/src/static_dist/index.html' doesn't exist

**Comment by lfrodrigues** [comment]
Updated README to show non-docker setup. Should be a lot more clear now.
