### ISSUE TITLE
Build Error with Yarn

### ISSUE THREAD

**Issue by kivo360** [Seedstars/django-react-redux-base#85]
I'm getting a build error with the Yarn package manager. It's in regards to babel. This is the error I'm getting: 

```bash
BabelLoaderError: SyntaxError: Unexpected token (17:4)

  15 | 
  16 | const node = (
> 17 |     <Root store={store} history={history} />
     |     ^
  18 | );
  19 | 
  20 | const token = sessionStorage.getItem('token');

```

By all logic, this react code should work right? I'm on Ubuntu 16.04 and all other parts of the build work. Cannot confirm if you all get the same error. Fails to build in docker too.

**Comment by lfrodrigues** [comment]
It looks like you have issues with Babel. Did yarn fail?

**Comment by kivo360** [comment]
Yes, Yarn did fail. I don't know what exactly is going on, yet babel is having major issues running. The problem is not with Postgresql, nor Django. Because I ran into this problem within both my Ubuntu operating system and Docker I'm assuming somebody ran into the issue and solved it at one point.

**Comment by lfrodrigues** [comment]
If yarn fails to install the packages webpack won't work. We're not getting this issue in any of the test machines we have. Please send a screenshot of the output of

```
$ yarn
```

**Comment by sgetachew** [comment]
Did you try delating the node_modules folders and run yarn again to install all the dependencies again.

**Comment by kivo360** [comment]
I just tried to do that. I'm still getting the same error. Here are my screen shots. Please let me know if you need more:

![screenshot from 2017-09-06 17 37 23](https://user-images.githubusercontent.com/2403240/30136036-2d22cdcc-932b-11e7-95e9-a01cd25617d4.png)

![screenshot from 2017-09-06 17 37 42](https://user-images.githubusercontent.com/2403240/30136035-2d0af382-932b-11e7-9134-c45382273bfd.png)

![screenshot from 2017-09-06 17 46 32](https://user-images.githubusercontent.com/2403240/30136082-5900da60-932b-11e7-9954-fc7d0fe9c473.png)

**Comment by lfrodrigues** [comment]
We're using node 6 LTS

```
$ wget -qO- https://deb.nodesource.com/setup_6.x | sudo bash -
``` 

Please be sure you are using our exact versions of software.
