### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by m2jobe** [Seedstars/django-react-redux-base#90]
I frequently get this error after running "yarn run dev" and running the server. 

This is the only error output : 
app.b8da97e0aa7de58fcb04.js:1 Uncaught SyntaxError: Unexpected token <
vendor.b8da97e0aa7de58fcb04.js:1 Uncaught SyntaxError: Unexpected token <

However sometimes it works when I ran "yarn run dev", not sure what im missing or why this occurs sometimes?

**Comment by lfrodrigues** [comment]
Please be sure you're using node LTS and that you have no error in the build process.

**Comment by m2jobe** [comment]
Im using node v6.11.3 and there is no error in the build process. When i use docker to run everything I dont run into this problem?

**Comment by lfrodrigues** [comment]
So it means you have something in your system that is causing the problem. That's why we use docker, to make sure everyone has a stable environment.
 
We use same version of nodejs but no errors :) 

What browser is showing the error?

**Comment by m2jobe** [comment]
Same error on firefox and chrome 
![image](https://user-images.githubusercontent.com/9561974/30563595-57f9febc-9c90-11e7-9a51-b3c7fbbaf306.png)

**Comment by m2jobe** [comment]
Ok I think I've got it working but still not sure why. Doing the following steps seems to get it working most of the time: 

- npm run dev
- python manage.py collectstatic
- sudo systemctl restart gunicorn

**Comment by lfrodrigues** [comment]
Ok, I see you're using gunicorn, you need to restart it every time you rebuild the js. 

In dev we run 
```
./manage.py runserver 
``` 

Closing this as you're not running the server as suggested in README. If you run the commands from README and still have problems please reopen.
